---
- name: Setup Web Servers
  hosts: webservers
  become: yes
  vars:
    http_port: 80
    domain_name: example.com
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Install required packages
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present
        
    - name: Configure nginx site
      template:
        src: templates/nginx-site.conf.j2
        dest: /etc/nginx/sites-available/{{ domain_name }}
      notify: Restart nginx
      
    - name: Enable site
      file:
        src: /etc/nginx/sites-available/{{ domain_name }}
        dest: /etc/nginx/sites-enabled/{{ domain_name }}
        state: link
      notify: Restart nginx
      
    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes
        
    - name: Set up SSL with Certbot
      command: >
        certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos 
        --email admin@{{ domain_name }} --redirect
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}
        
    - name: Set up cron job for certificate renewal
      cron:
        name: "Certbot renewal"
        special_time: daily
        job: "certbot renew --quiet --no-self-upgrade"
        
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted